//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSLIPConf.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSLIPConf.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WSLIPConf.
        /// </summary>
        internal static string AboutLong {
            get {
                return ResourceManager.GetString("AboutLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Family.
        /// </summary>
        internal static string AddressFamily {
            get {
                return ResourceManager.GetString("AddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Rule.
        /// </summary>
        internal static string AddRule {
            get {
                return ResourceManager.GetString("AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Rules.
        /// </summary>
        internal static string ApplyRules {
            get {
                return ResourceManager.GetString("ApplyRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Apply Changes.
        /// </summary>
        internal static string AutoApply {
            get {
                return ResourceManager.GetString("AutoApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic WSL Destination.
        /// </summary>
        internal static string AutoDest {
            get {
                return ResourceManager.GetString("AutoDest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto IP.
        /// </summary>
        internal static string AutoIP {
            get {
                return ResourceManager.GetString("AutoIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto IP: {0}.
        /// </summary>
        internal static string AutoIPX {
            get {
                return ResourceManager.GetString("AutoIPX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Rules.
        /// </summary>
        internal static string ClearRules {
            get {
                return ResourceManager.GetString("ClearRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click To Copy To Clipboard.
        /// </summary>
        internal static string Click_To_Copy {
            get {
                return ResourceManager.GetString("Click_To_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all rules?.
        /// </summary>
        internal static string ConfirmClearRules {
            get {
                return ResourceManager.GetString("ConfirmClearRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reload the rules?
        ///Unsaved changes will be discarded..
        /// </summary>
        internal static string ConfirmReloadRules {
            get {
                return ResourceManager.GetString("ConfirmReloadRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected rules?.
        /// </summary>
        internal static string ConfirmRemoveRules {
            get {
                return ResourceManager.GetString("ConfirmRemoveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy IPv4 Address.
        /// </summary>
        internal static string CopyIPAddress {
            get {
                return ResourceManager.GetString("CopyIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy IPv6 Address.
        /// </summary>
        internal static string CopyIPV6Address {
            get {
                return ResourceManager.GetString("CopyIPV6Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Rules.
        /// </summary>
        internal static string DeleteRule {
            get {
                return ResourceManager.GetString("DeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Address Family.
        /// </summary>
        internal static string DestAddressFamily {
            get {
                return ResourceManager.GetString("DestAddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Address.
        /// </summary>
        internal static string DestinationAddress {
            get {
                return ResourceManager.GetString("DestinationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Port.
        /// </summary>
        internal static string DestinationPort {
            get {
                return ResourceManager.GetString("DestinationPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Rule.
        /// </summary>
        internal static string EditRule {
            get {
                return ResourceManager.GetString("EditRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Rules.
        /// </summary>
        internal static string EditRules {
            get {
                return ResourceManager.GetString("EditRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error applying rules!.
        /// </summary>
        internal static string ErrorApplying {
            get {
                return ResourceManager.GetString("ErrorApplying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors on the page and the item cannot be saved!.
        /// </summary>
        internal static string ErrorCannotSave {
            get {
                return ResourceManager.GetString("ErrorCannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be blank..
        /// </summary>
        internal static string ErrorFieldBlank {
            get {
                return ResourceManager.GetString("ErrorFieldBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value for this field is in an incorrect format..
        /// </summary>
        internal static string ErrorInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for this field is invalid..
        /// </summary>
        internal static string ErrorInvalidValue {
            get {
                return ResourceManager.GetString("ErrorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the wrong kind of IP address for the selected address family..
        /// </summary>
        internal static string ErrorWrongAddress {
            get {
                return ResourceManager.GetString("ErrorWrongAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Current Rules.
        /// </summary>
        internal static string GetCurrentRules {
            get {
                return ResourceManager.GetString("GetCurrentRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current WSL IP Address: {1}.
        /// </summary>
        internal static string IconTip {
            get {
                return ResourceManager.GetString("IconTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4 Address Copied!.
        /// </summary>
        internal static string IPAddressCopied {
            get {
                return ResourceManager.GetString("IPAddressCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv4.
        /// </summary>
        internal static string IPv4 {
            get {
                return ResourceManager.GetString("IPv4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6.
        /// </summary>
        internal static string IPv6 {
            get {
                return ResourceManager.GetString("IPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 Address Copied!.
        /// </summary>
        internal static string IPV6AddressCopied {
            get {
                return ResourceManager.GetString("IPV6AddressCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSL Port Binding Tool.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode {0} To {1}.
        /// </summary>
        internal static string Mode_X_To_X {
            get {
                return ResourceManager.GetString("Mode_X_To_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule Definition.
        /// </summary>
        internal static string NewRuleDefinition {
            get {
                return ResourceManager.GetString("NewRuleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IPv6 Address Detected.
        /// </summary>
        internal static string No_V6_Detected {
            get {
                return ResourceManager.GetString("No_V6_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protocol.
        /// </summary>
        internal static string Protocol {
            get {
                return ResourceManager.GetString("Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy Type.
        /// </summary>
        internal static string ProxyType {
            get {
                return ResourceManager.GetString("ProxyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh and Apply.
        /// </summary>
        internal static string RefreshAndApply {
            get {
                return ResourceManager.GetString("RefreshAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh IP.
        /// </summary>
        internal static string RefreshIP {
            get {
                return ResourceManager.GetString("RefreshIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh WSL IP Address.
        /// </summary>
        internal static string RefreshWSLIP {
            get {
                return ResourceManager.GetString("RefreshWSLIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Apply Rules.
        /// </summary>
        internal static string Rerun {
            get {
                return ResourceManager.GetString("Rerun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules applied successfully!.
        /// </summary>
        internal static string RulesApplied {
            get {
                return ResourceManager.GetString("RulesApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run On Startup.
        /// </summary>
        internal static string RunOnStartup {
            get {
                return ResourceManager.GetString("RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Window.
        /// </summary>
        internal static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Address.
        /// </summary>
        internal static string SourceAddress {
            get {
                return ResourceManager.GetString("SourceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Address Family.
        /// </summary>
        internal static string SourceAddressFamily {
            get {
                return ResourceManager.GetString("SourceAddressFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Port.
        /// </summary>
        internal static string SourcePort {
            get {
                return ResourceManager.GetString("SourcePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tcp.
        /// </summary>
        internal static string Tcp {
            get {
                return ResourceManager.GetString("Tcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udp.
        /// </summary>
        internal static string Udp {
            get {
                return ResourceManager.GetString("Udp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSL IPv4 Address.
        /// </summary>
        internal static string WSLAddress {
            get {
                return ResourceManager.GetString("WSLAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon wslip {
            get {
                object obj = ResourceManager.GetObject("wslip", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WSL IPv6 Address.
        /// </summary>
        internal static string WSLV6Address {
            get {
                return ResourceManager.GetString("WSLV6Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} To {1}.
        /// </summary>
        internal static string X_To_X {
            get {
                return ResourceManager.GetString("X_To_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
